//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoyaltyShares_API.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Registered_Clients
    {
        public int ID { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string Company_Name { get; set; }
        public string Vat_Number { get; set; }
        public string Contact_Number { get; set; }
        public string AddressLine_1 { get; set; }
        public string AddressLine_2 { get; set; }
        public string AddressLine_3 { get; set; }
        public string City { get; set; }
        public string PostalCode { get; set; }
        public string Suburb { get; set; }
        public Nullable<System.Guid> Client_ID { get; set; }
    }
}
